baseURL = "https://mezpahlan.github.io/"
disablePathToLower = true
languageCode = "en-gb"
title = "Mez Says"
theme = "hyde"
paginateSize = 7
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
rssLimit = 10

[params]
  description = "Staff Engineer specialising in Android and Experimentation based in Bristol, UK."
  [params.author]
    name = "Mez Pahlan"

[menus]
  main = [
      { Weight = 4, Name = "mastodon", URL = "https://androiddev.social/@mez" },
      { Weight = 5, Name = "linkedin", URL = "https://www.linkedin.com/in/mezpahlan" },
      { Weight = 6, Name = "github", URL = "https://github.com/mezpahlan" }
  ]

  [outputFormats]
    [outputFormats.RSS]
      mediatype = "application/rss"
      baseName = "rss"

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = true
